# Generated by Django 5.1 on 2024-12-12 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Busname', models.CharField(max_length=255)),
                ('Bus_NO', models.CharField(max_length=225)),
                ('Owner', models.CharField(max_length=225)),
                ('route_start', models.CharField(max_length=225)),
                ('route_end', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BusPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_lat', models.FloatField()),
                ('current_lng', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='app.buses')),
            ],
        ),
        migrations.CreateModel(
            name='BusStopsig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('index', models.IntegerField()),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='app.buses')),
            ],
        ),
    ]
